version: '3'

networks: 
  inside:
    external: false

services:
  db_mysql:
    container_name: db_mysql
    image: mysql:5.7
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-teste}"
      MYSQL_USER: "${MYSQL_USER:-teste}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-teste}"
    networks: 
      - inside
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
  apacheweb:
    build: .
    container_name: ap_web
    networks: 
      - inside
    depends_on:
      - db_mysql
    volumes:
      - ./files:/var/www/files
      - /etc/localtime:/etc/localtime
      - ./logs/apache:/var/log/apache2
    restart: always
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      - "${SMTP_SSL_PORT:-465}:465"
      - "${SMTP_TLS_PORT:-587}:587"
    stdin_open: true
    tty: true